- block:

    - name: homebrew tap
      homebrew_tap:
        name: '{{ item }}'
        state: present
      with_items: '{{ homebrew_taps }}'

    - name: homebrew packages install
      homebrew:
        name: '{{ item.name }}'
        state: '{{ item.state | default("present") }}'
      with_items: '{{ homebrew_packages }}'

    - name: homebrew cask packages install
      become: '{{ item.become | default("no") }}'
      become_user: "{{ lookup('env', 'USER') }}"
      homebrew_cask:
        name: "{{ item.name }}"
        state: installed
      environment:
        HOMEBREW_CASK_OPTS: "--appdir=/Applications"
      with_items: '{{ homebrew_cask_packages }}'

  tags:
    - homebrew
